//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaMarketplace.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class copyright
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public copyright()
        {
            this.copyright_sales = new HashSet<copyright_sales>();
            this.license_sales = new HashSet<license_sales>();
            this.licenses = new HashSet<license>();
        }
    
        public int copyright_id { get; set; }
        public string copyright_media_type { get; set; }
        public string copyright_file { get; set; }
        public int copyright_user_id { get; set; }
        public bool copyright_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<copyright_sales> copyright_sales { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<license_sales> license_sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<license> licenses { get; set; }
    }
}
