//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaMarketplace.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class copyright_sales
    {
        public int copyright_sale_id { get; set; }
        public int copyright_sale_copyright_id { get; set; }
        public int copyright_sale_seller_id { get; set; }
        public Nullable<int> copyright_sale_buyer_id { get; set; }
        public System.DateTime copyright_sale_create_date { get; set; }
        public Nullable<System.DateTime> copyright_sale_close_date { get; set; }
        public decimal copyright_sale_sale_price { get; set; }
    
        public virtual user user { get; set; }
        public virtual copyright copyright { get; set; }
        public virtual user user1 { get; set; }
    }
}
