//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaMarketplace.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class license_sales
    {
        public int license_sale_id { get; set; }
        public string license_sale_type { get; set; }
        public int license_sale_buyer_id { get; set; }
        public int license_sale_copyright_id { get; set; }
        public System.DateTime license_sale_start_date { get; set; }
        public System.DateTime license_sale_end_date { get; set; }
        public decimal license_sale_sales_price { get; set; }
        public System.DateTime license_sale_create_date { get; set; }
    
        public virtual copyright copyright { get; set; }
        public virtual user user { get; set; }
    }
}
