//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaMarketplace.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class license
    {
        public int license_id { get; set; }
        public string license_type { get; set; }
        public int license_copyright_id { get; set; }
        public System.DateTime license_start_date { get; set; }
        public System.DateTime license_end_date { get; set; }
        public decimal license_cost { get; set; }
    
        public virtual copyright copyright { get; set; }
    }
}
