//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaMarketplace.Models.EntityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MediaMarketplaceEntities : DbContext
    {
        public MediaMarketplaceEntities()
            : base("name=MediaMarketplaceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<copyright_sales> copyright_sales { get; set; }
        public virtual DbSet<copyright> copyrights { get; set; }
        public virtual DbSet<license_sales> license_sales { get; set; }
        public virtual DbSet<license> licenses { get; set; }
        public virtual DbSet<payment_informations> payment_informations { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
