//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaMarketplace.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_informations
    {
        public int payment_information_id { get; set; }
        public int payment_information_user_id { get; set; }
        public string payment_information_bank_account { get; set; }
        public string payment_information_routing_number { get; set; }
    
        public virtual user user { get; set; }
    }
}
