//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaMarketplace.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_copyrights
    {
        public int copyright_id { get; set; }
        public string copyright_name { get; set; }
        public string copyright_media_type { get; set; }
        public string copyright_file { get; set; }
        public int copyright_user_id { get; set; }
    }
}
